# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: jrs-a
email: albertojamaicarose@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  portfolio
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://jrs-a.github.io" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  jrs-a
collections_dir: collections

header_pages:
  - index.md
  - projects.md

collections:
  featured:
  socials:
    order:
      - email.md
      - linkedin.md
      - github.md

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-pdf-embed

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/